// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreatePostInput struct {
	UserID string `json:"userId"`
	Body   string `json:"body"`
}

type CreateUserInput struct {
	Name string `json:"name"`
}

type Pagination struct {
	Skip int `json:"skip"`
	Take int `json:"take"`
}

type Post struct {
	ID        string    `json:"id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	User      *User     `json:"user"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Posts []*Post `json:"posts"`
}
